-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jul 22, 2023 at 08:08 AM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `random_recipe_generator`
--

-- --------------------------------------------------------

--
-- Table structure for table `recipes`
--

CREATE TABLE `recipes` (
  `id` int(11) NOT NULL,
  `name` varchar(100) NOT NULL,
  `cuisine` varchar(50) NOT NULL,
  `course` varchar(50) NOT NULL,
  `dietary_preference` varchar(50) NOT NULL,
  `instructions` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `recipes`
--

INSERT INTO `recipes` (`id`, `name`, `cuisine`, `course`, `dietary_preference`, `instructions`) VALUES
(1, 'Spaghetti Carbonara', 'Italian', 'Main Course', 'Non-Vegetarian', '1. Cook spaghetti according to package instructions. \n2. In a bowl, mix eggs, grated cheese, black pepper, and chopped bacon. \n3. Drain cooked spaghetti and immediately toss it with the egg mixture. \n4. The heat from the spaghetti will cook the eggs and create a creamy sauce. \n5. Serve hot and enjoy!'),
(2, 'Vegetable Biryani', 'Indian', 'Main Course', 'Vegetarian', '1. Soak basmati rice for 30 minutes and drain. \n2. In a large pot, layer cooked vegetables and rice with saffron-infused milk and fried onions. \n3. Cover and cook on low heat until the rice is fully cooked and fragrant. \n4. Serve hot with raita and enjoy!'),
(3, 'Tacos Al Pastor', 'Mexican', 'Main Course', 'Non-Vegetarian', '1. Marinate thinly sliced pork with pineapple, onions, and spices. \n2. Grill the marinated pork until tender and slightly charred. \n3. Warm corn tortillas and fill them with the grilled pork and your favorite toppings. \n4. Serve with salsa and lime wedges. Enjoy your delicious tacos!'),
(4, 'Chocolate Brownies', 'Dessert', 'Dessert', 'Vegetarian', '1. Melt butter and chocolate in a double boiler. \n2. Mix in sugar, eggs, and vanilla until well combined. \n3. Add flour and cocoa powder and fold until just combined. \n4. Pour the batter into a greased baking pan and bake until a toothpick inserted in the center comes out with moist crumbs. \n5. Let it cool, cut into squares, and enjoy your gooey chocolate brownies!'),
(5, 'Vegan Lentil Soup', 'Any', 'Main Course', 'Vegan', '1. Sauté onions, garlic, carrots, and celery in olive oil until softened. \n2. Add lentils, vegetable broth, tomatoes, and your favorite spices. \n3. Bring to a boil, then simmer until the lentils are tender. \n4. Adjust seasonings to taste and serve hot with a sprinkle of fresh herbs. Enjoy your hearty vegan lentil soup!'),
(6, 'Spaghetti Carbonara', 'Italian', 'Main Course', 'Non-Vegetarian', '1. Cook spaghetti according to package instructions. \n2. In a bowl, mix eggs, grated cheese, black pepper, and chopped bacon. \n3. Drain cooked spaghetti and immediately toss it with the egg mixture. \n4. The heat from the spaghetti will cook the eggs and create a creamy sauce. \n5. Serve hot and enjoy!'),
(7, 'Vegetable Biryani', 'Indian', 'Main Course', 'Vegetarian', '1. Soak basmati rice for 30 minutes and drain. \n2. In a large pot, layer cooked vegetables and rice with saffron-infused milk and fried onions. \n3. Cover and cook on low heat until the rice is fully cooked and fragrant. \n4. Serve hot with raita and enjoy!'),
(8, 'Tacos Al Pastor', 'Mexican', 'Main Course', 'Non-Vegetarian', '1. Marinate thinly sliced pork with pineapple, onions, and spices. \n2. Grill the marinated pork until tender and slightly charred. \n3. Warm corn tortillas and fill them with the grilled pork and your favorite toppings. \n4. Serve with salsa and lime wedges. Enjoy your delicious tacos!'),
(9, 'Chocolate Brownies', 'Dessert', 'Dessert', 'Vegetarian', '1. Melt butter and chocolate in a double boiler. \n2. Mix in sugar, eggs, and vanilla until well combined. \n3. Add flour and cocoa powder and fold until just combined. \n4. Pour the batter into a greased baking pan and bake until a toothpick inserted in the center comes out with moist crumbs. \n5. Let it cool, cut into squares, and enjoy your gooey chocolate brownies!'),
(10, 'Vegan Lentil Soup', 'Any', 'Main Course', 'Vegan', '1. Sauté onions, garlic, carrots, and celery in olive oil until softened. \n2. Add lentils, vegetable broth, tomatoes, and your favorite spices. \n3. Bring to a boil, then simmer until the lentils are tender. \n4. Adjust seasonings to taste and serve hot with a sprinkle of fresh herbs. Enjoy your hearty vegan lentil soup!'),
(11, 'Spaghetti Carbonara', 'Italian', 'Main Course', 'Non-Vegetarian', '1. Cook spaghetti according to package instructions. \n2. In a bowl, mix eggs, grated cheese, black pepper, and chopped bacon. \n3. Drain cooked spaghetti and immediately toss it with the egg mixture. \n4. The heat from the spaghetti will cook the eggs and create a creamy sauce. \n5. Serve hot and enjoy!'),
(12, 'Vegetable Biryani', 'Indian', 'Main Course', 'Vegetarian', '1. Soak basmati rice for 30 minutes and drain. \n2. In a large pot, layer cooked vegetables and rice with saffron-infused milk and fried onions. \n3. Cover and cook on low heat until the rice is fully cooked and fragrant. \n4. Serve hot with raita and enjoy!'),
(13, 'Tacos Al Pastor', 'Mexican', 'Main Course', 'Non-Vegetarian', '1. Marinate thinly sliced pork with pineapple, onions, and spices. \n2. Grill the marinated pork until tender and slightly charred. \n3. Warm corn tortillas and fill them with the grilled pork and your favorite toppings. \n4. Serve with salsa and lime wedges. Enjoy your delicious tacos!'),
(14, 'Chocolate Brownies', 'Dessert', 'Dessert', 'Vegetarian', '1. Melt butter and chocolate in a double boiler. \n2. Mix in sugar, eggs, and vanilla until well combined. \n3. Add flour and cocoa powder and fold until just combined. \n4. Pour the batter into a greased baking pan and bake until a toothpick inserted in the center comes out with moist crumbs. \n5. Let it cool, cut into squares, and enjoy your gooey chocolate brownies!'),
(15, 'Vegan Lentil Soup', 'Any', 'Main Course', 'Vegan', '1. Sauté onions, garlic, carrots, and celery in olive oil until softened. \n2. Add lentils, vegetable broth, tomatoes, and your favorite spices. \n3. Bring to a boil, then simmer until the lentils are tender. \n4. Adjust seasonings to taste and serve hot with a sprinkle of fresh herbs. Enjoy your hearty vegan lentil soup!'),
(16, 'Chicken Parmesan', 'Italian', 'Main Course', 'Non-Vegetarian', '1. Bread chicken cutlets with breadcrumbs and seasonings. \n2. Fry the breaded chicken until golden brown and cooked through. \n3. Top with marinara sauce and mozzarella cheese. \n4. Bake until the cheese is melted and bubbly. \n5. Serve over cooked spaghetti or on a sandwich roll.'),
(17, 'Paneer Tikka Masala', 'Indian', 'Main Course', 'Vegetarian', '1. Marinate paneer cubes with yogurt, spices, and lemon juice. \n2. Thread the marinated paneer onto skewers and grill until lightly charred. \n3. Prepare a creamy tomato-based sauce with onions, tomatoes, and spices. \n4. Add the grilled paneer to the sauce and simmer until heated through. \n5. Garnish with fresh cilantro and serve with naan or rice.'),
(18, 'Shrimp Ceviche', 'Mexican', 'Appetizer', 'Non-Vegetarian', '1. Cook shrimp in boiling water until pink and opaque. \n2. Dice cooked shrimp and combine with chopped tomatoes, onions, cucumbers, and cilantro. \n3. Dress with lime juice, orange juice, and hot sauce. \n4. Refrigerate for at least 30 minutes to let the flavors meld. \n5. Serve chilled with tortilla chips or tostadas.'),
(19, 'Tiramisu', 'Italian', 'Dessert', 'Vegetarian', '1. Brew strong coffee and let it cool. \n2. Beat mascarpone cheese, sugar, and vanilla extract until smooth. \n3. Dip ladyfingers in coffee and layer them in a dish. \n4. Spread a layer of the mascarpone mixture over the ladyfingers. \n5. Repeat the layers and dust the top with cocoa powder. \n6. Chill for a few hours before serving.'),
(20, 'Chana Masala', 'Indian', 'Main Course', 'Vegan', '1. Sauté onions, garlic, and ginger in oil until softened. \n2. Add spices and cook until fragrant. \n3. Add cooked chickpeas, tomatoes, and water. \n4. Simmer until the chickpeas are tender and the sauce thickens. \n5. Garnish with chopped cilantro and serve with rice or naan.'),
(21, 'Guacamole', 'Mexican', 'Appetizer', 'Vegetarian', '1. Mash ripe avocados with lime juice and salt. \n2. Mix in chopped tomatoes, onions, cilantro, and jalapeño (if desired). \n3. Adjust seasoning to taste. \n4. Serve with tortilla chips or as a topping for tacos and burritos.'),
(22, 'Mango Lassi', 'Indian', 'Beverage', 'Vegetarian', '1. Blend ripe mangoes, yogurt, sugar, and a pinch of cardamom in a blender. \n2. Add a splash of milk or water to achieve the desired consistency. \n3. Serve chilled and garnish with a slice of mango.'),
(23, 'Enchiladas', 'Mexican', 'Main Course', 'Any', '1. Sauté onions and garlic until softened. \n2. Add cooked chicken or vegetables, along with spices and enchilada sauce. \n3. Fill tortillas with the mixture, roll them up, and place them in a baking dish. \n4. Pour additional sauce over the enchiladas and top with cheese. \n5. Bake until the cheese is melted and bubbly.'),
(24, 'Pav Bhaji', 'Indian', 'Main Course', 'Vegetarian', '1. Boil and mash mixed vegetables (potatoes, peas, carrots, cauliflower, etc.). \n2. Sauté onions, garlic, and ginger until golden brown. \n3. Add tomatoes and spices, and cook until the tomatoes break down. \n4. Add the mashed vegetables and pav bhaji masala. \n5. Cook until the flavors meld. Serve with buttered pav buns and chopped onions.'),
(25, 'Churros', 'Mexican', 'Dessert', 'Vegetarian', '1. Heat water, butter, sugar, and salt in a saucepan until the butter melts. \n2. Stir in flour until a dough forms. \n3. Pipe the dough into hot oil and fry until golden brown and crispy. \n4. Roll the churros in cinnamon-sugar. \n5. Serve with chocolate sauce for dipping.'),
(26, 'Palak Paneer', 'Indian', 'Main Course', 'Vegetarian', '1. Blanch spinach and blend it into a puree. \n2. Sauté onions, garlic, and ginger until golden brown. \n3. Add spices and cook until fragrant. \n4. Stir in the spinach puree and paneer cubes. \n5. Simmer until the paneer is heated through and the flavors blend. Serve with rice or naan.'),
(27, 'Ceviche de Camarón', 'Mexican', 'Appetizer', 'Non-Vegetarian', '1. Cook shrimp in lime juice until pink and opaque. \n2. Mix in chopped tomatoes, onions, cilantro, and jalapeño. \n3. Season with salt and pepper. \n4. Serve chilled with tostadas or saltine crackers.'),
(28, 'Rasmalai', 'Indian', 'Dessert', 'Vegetarian', '1. Boil milk and curdle it with lemon juice. \n2. Strain the curds and rinse with water to remove the lemony taste. \n3. Knead the curds into smooth balls and flatten them slightly. \n4. Boil the flattened balls in sugar syrup until they puff up. \n5. Soak the cooked balls in flavored milk. \n6. Garnish with chopped nuts and serve chilled.'),
(29, 'Fish Tacos', 'Mexican', 'Main Course', 'Non-Vegetarian', '1. Coat fish fillets in a seasoned batter. \n2. Fry the fish until crispy and cooked through. \n3. Warm corn tortillas and fill them with the fried fish and slaw. \n4. Drizzle with a creamy sauce. \n5. Serve with lime wedges.'),
(30, 'Aloo Gobi', 'Indian', 'Main Course', 'Vegetarian', '1. Sauté onions, garlic, and ginger until softened. \n2. Add spices and cook until fragrant. \n3. Stir in chopped potatoes and cauliflower. \n4. Cover and cook until the vegetables are tender. \n5. Garnish with fresh cilantro and serve with rice or naan.'),
(31, 'Mexican Street Corn', 'Mexican', 'Appetizer', 'Vegetarian', '1. Grill corn on the cob until charred. \n2. Spread a mixture of mayonnaise, sour cream, and lime juice over the grilled corn. \n3. Sprinkle with cotija cheese and chili powder. \n4. Serve with lime wedges.'),
(32, 'Butter Chicken', 'Indian', 'Main Course', 'Non-Vegetarian', '1. Marinate chicken pieces in yogurt, spices, and lemon juice. \n2. Grill or cook the marinated chicken until cooked through. \n3. Prepare a rich tomato-based sauce with onions, garlic, ginger, and spices. \n4. Add the cooked chicken to the sauce and simmer until heated through. \n5. Serve with naan or rice.'),
(33, 'Tres Leches Cake', 'Mexican', 'Dessert', 'Vegetarian', '1. Bake a sponge cake and let it cool. \n2. Poke holes in the cake and soak it with a mixture of three milks (evaporated milk, sweetened condensed milk, and heavy cream). \n3. Refrigerate to allow the cake to absorb the milk. \n4. Top with whipped cream and serve with fresh fruit.'),
(34, 'Matar Paneer', 'Indian', 'Main Course', 'Vegetarian', '1. Sauté onions, garlic, and ginger until golden brown. \n2. Add spices and cook until fragrant. \n3. Stir in chopped tomatoes and peas. \n4. Add paneer cubes and simmer until heated through. \n5. Garnish with chopped cilantro and serve with rice or naan.'),
(35, 'Chicken Quesadillas', 'Mexican', 'Main Course', 'Non-Vegetarian', '1. Cook chicken until fully cooked and shred it. \n2. Mix the shredded chicken with cheese, onions, and bell peppers. \n3. Spread the mixture between two flour tortillas. \n4. Cook the quesadillas until the cheese is melted and the tortillas are crispy. \n5. Cut into wedges and serve with salsa and sour cream.'),
(36, 'Rajma Chawal', 'Indian', 'Main Course', 'Vegetarian', '1. Soak kidney beans (rajma) overnight and cook until tender. \n2. Sauté onions, garlic, and ginger until softened. \n3. Add tomatoes, spices, and cooked rajma. \n4. Simmer until the flavors meld. \n5. Serve with steamed rice and garnish with chopped cilantro.'),
(37, 'Mexican Rice', 'Mexican', 'Side Dish', 'Vegetarian', '1. Sauté onions and garlic until softened. \n2. Add rice and cook until lightly toasted. \n3. Stir in diced tomatoes, vegetable broth, and spices. \n4. Simmer until the rice is fully cooked. \n5. Fluff the rice with a fork and garnish with chopped cilantro.'),
(38, 'Mango Salsa', 'Mexican', 'Appetizer', 'Vegetarian', '1. Dice ripe mangoes, tomatoes, onions, and cilantro. \n2. Mix with lime juice, salt, and a pinch of cayenne pepper for some heat. \n3. Refrigerate to let the flavors meld. \n4. Serve with tortilla chips or as a topping for grilled chicken or fish.'),
(39, 'Chicken Curry', 'Indian', 'Main Course', 'Non-Vegetarian', '1. Sauté onions, garlic, and ginger until golden brown. \n2. Add spices and cook until fragrant. \n3. Stir in chopped tomatoes and cook until they break down. \n4. Add chicken pieces and cook until fully cooked. \n5. Garnish with chopped cilantro and serve with rice or naan.'),
(40, 'Chiles Rellenos', 'Mexican', 'Main Course', 'Vegetarian', '1. Roast poblano peppers and remove the skins. \n2. Stuff the peppers with cheese or a cheese and vegetable mixture. \n3. Dip the stuffed peppers in batter and fry until golden brown. \n4. Serve with tomato sauce or salsa.'),
(41, 'Aloo Paratha', 'Indian', 'Main Course', 'Vegetarian', '1. Make a dough with wheat flour and water. \n2. Roll out the dough and place a filling of spiced mashed potatoes in the center. \n3. Seal the dough and roll out the paratha. \n4. Cook the paratha on a hot griddle until both sides are golden brown. \n5. Serve with yogurt and pickles.'),
(42, 'Flan', 'Mexican', 'Dessert', 'Vegetarian', '1. Make caramel by melting sugar until golden brown. \n2. Pour the caramel into ramekins. \n3. Prepare a custard mixture with eggs, condensed milk, evaporated milk, and vanilla. \n4. Pour the custard over the caramel in the ramekins. \n5. Bake until the flan is set. \n6. Refrigerate and invert the ramekins to serve.'),
(43, 'Gulab Jamun', 'Indian', 'Dessert', 'Vegetarian', '1. Mix milk powder, all-purpose flour, and baking soda. \n2. Add ghee and milk to form a dough. \n3. Shape the dough into small balls. \n4. Fry the balls until golden brown and soak them in sugar syrup. \n5. Garnish with chopped nuts and serve warm.'),
(44, 'Beef Tacos', 'Mexican', 'Main Course', 'Non-Vegetarian', '1. Cook ground beef with onions, garlic, and spices until fully cooked. \n2. Warm corn tortillas and fill them with the seasoned beef and toppings. \n3. Serve with salsa and lime wedges.'),
(45, 'Dal Makhani', 'Indian', 'Main Course', 'Vegetarian', '1. Soak black lentils (urad dal) and kidney beans (rajma) overnight and cook until tender. \n2. Sauté onions, garlic, and ginger until softened. \n3. Add tomatoes and spices, and cook until the tomatoes break down. \n4. Stir in the cooked lentils and beans. \n5. Add cream and butter for richness. \n6. Simmer until the flavors meld. Serve with rice or naan.'),
(46, 'Queso Blanco', 'Mexican', 'Appetizer', 'Vegetarian', '1. Heat milk until it begins to steam. \n2. Add vinegar or lemon juice to curdle the milk. \n3. Drain the whey and press the curds into a mold. \n4. Refrigerate until firm. \n5. Slice or crumble the queso blanco and serve as a cheese dip or topping.'),
(47, 'Rogan Josh', 'Indian', 'Main Course', 'Non-Vegetarian', '1. Sauté onions, garlic, and ginger until golden brown. \n2. Add spices and cook until fragrant. \n3. Stir in chopped tomatoes and cook until they break down. \n4. Add cubed lamb and cook until tender. \n5. Garnish with chopped cilantro and serve with rice or naan.'),
(48, 'Chimichangas', 'Mexican', 'Main Course', 'Any', '1. Cook chicken or beef with onions, garlic, and spices until fully cooked. \n2. Fill flour tortillas with the cooked meat and refried beans. \n3. Fold the tortillas into burrito-like shapes. \n4. Fry the chimichangas until crispy and golden brown. \n5. Serve with guacamole and sour cream.'),
(49, 'Dum Aloo', 'Indian', 'Main Course', 'Vegetarian', '1. Parboil baby potatoes and deep fry until golden brown. \n2. Sauté onions, garlic, and ginger until golden brown. \n3. Add spices and cook until fragrant. \n4. Stir in chopped tomatoes and cook until they break down. \n5. Add the fried potatoes and simmer until the flavors meld. \n6. Garnish with chopped cilantro and serve with rice or naan.'),
(50, 'Chile Verde', 'Mexican', 'Main Course', 'Any', '1. Cook pork, onions, garlic, and spices until the pork is fully cooked. \n2. Add green chilies, tomatillos, and broth. \n3. Simmer until the flavors meld and the sauce thickens. \n4. Serve with rice or warm tortillas.'),
(51, 'Mysore Pak', 'Indian', 'Dessert', 'Vegetarian', '1. Heat ghee and chickpea flour (besan) in a pan. \n2. Add sugar and water to form a smooth mixture. \n3. Cook the mixture until it thickens. \n4. Pour the mixture into a greased dish and let it set. \n5. Cut into squares and serve.'),
(52, 'Chicken Fajitas', 'Mexican', 'Main Course', 'Non-Vegetarian', '1. Marinate chicken strips with lime juice, garlic, and spices. \n2. Sauté the marinated chicken with bell peppers and onions until fully cooked. \n3. Warm flour tortillas and fill them with the chicken and veggies. \n4. Serve with salsa, guacamole, and sour cream.'),
(53, 'Chole Bhature', 'Indian', 'Main Course', 'Vegetarian', '1. Soak chickpeas (chole) overnight and cook until tender. \n2. Sauté onions, garlic, and ginger until softened. \n3. Add tomatoes and spices, and cook until the tomatoes break down. \n4. Stir in the cooked chickpeas. \n5. Prepare fluffy bhature (fried bread) to serve with the chole.'),
(54, 'Tostadas', 'Mexican', 'Main Course', 'Any', '1. Fry corn tortillas until crispy. \n2. Top the tostadas with refried beans, lettuce, tomatoes, cheese, and your choice of meat (chicken, beef, or pork). \n3. Drizzle with hot sauce or salsa. \n4. Serve as an open-faced taco.'),
(55, 'Kheer', 'Indian', 'Dessert', 'Vegetarian', '1. Boil milk and add rice or vermicelli. \n2. Cook until the rice or vermicelli is fully cooked and the milk thickens. \n3. Add sugar, cardamom, and nuts. \n4. Serve chilled as a creamy rice pudding.'),
(56, 'Sopes', 'Mexican', 'Main Course', 'Any', '1. Prepare a dough with masa harina and water. \n2. Shape the dough into small rounds and form a raised edge. \n3. Fry the sopes until golden brown. \n4. Fill the sopes with beans, meat, lettuce, cheese, and salsa. \n5. Serve as a tasty handheld meal.'),
(57, 'Rava Kesari', 'Indian', 'Dessert', 'Vegetarian', '1. Roast semolina (rava) in ghee until fragrant. \n2. Add sugar and water to form a smooth mixture. \n3. Cook until the mixture thickens. \n4. Add saffron, cardamom, and nuts. \n5. Serve warm or chilled.'),
(58, 'Mexican Corn Salad', 'Mexican', 'Appetizer', 'Vegetarian', '1. Mix corn kernels with mayonnaise, sour cream, lime juice, and chili powder. \n2. Stir in chopped cilantro and cotija cheese. \n3. Serve as a refreshing and tangy salad.'),
(59, 'Gobi Manchurian', 'Indian', 'Appetizer', 'Vegetarian', '1. Coat cauliflower florets in a spiced batter. \n2. Fry the cauliflower until crispy. \n3. Prepare a tangy sauce with onions, garlic, ginger, and soy sauce. \n4. Toss the fried cauliflower in the sauce. \n5. Garnish with chopped green onions and serve as an appetizer.'),
(60, 'Shrimp Curry', 'Indian', 'Main Course', 'Non-Vegetarian', '1. Sauté onions, garlic, and ginger until softened. \n2. Add spices and cook until fragrant. \n3. Stir in chopped tomatoes and cook until they break down. \n4. Add shrimp and cook until fully cooked. \n5. Garnish with chopped cilantro and serve with rice or naan.'),
(61, 'Chilaquiles', 'Mexican', 'Main Course', 'Any', '1. Fry tortilla chips until crispy. \n2. Toss the chips in red or green salsa until lightly coated. \n3. Top with shredded cheese, sour cream, and sliced onions. \n4. Serve with fried or scrambled eggs for a hearty breakfast or brunch.'),
(62, 'Mutton Biryani', 'Indian', 'Main Course', 'Non-Vegetarian', '1. Marinate mutton pieces with yogurt, spices, and lemon juice. \n2. Sauté onions and garlic until golden brown. \n3. Layer cooked mutton and rice with saffron-infused milk, fried onions, and mint leaves. \n4. Cover and cook on low heat until the rice is fully cooked and fragrant. \n5. Serve with raita and enjoy!'),
(63, 'Tamales', 'Mexican', 'Main Course', 'Any', '1. Prepare a dough with masa harina, broth, and lard. \n2. Spread the dough on corn husks and fill with meat, beans, or cheese. \n3. Wrap the tamales and steam until cooked through. \n4. Serve with salsa and sour cream.'),
(64, 'Mango Chutney', 'Indian', 'Side Dish', 'Vegetarian', '1. Dice ripe mangoes and cook them with sugar, vinegar, and spices. \n2. Simmer until the mixture thickens and the mangoes are soft. \n3. Serve as a tangy and sweet condiment with various dishes.'),
(65, 'Mexican Wedding Cookies', 'Mexican', 'Dessert', 'Vegetarian', '1. Mix butter, powdered sugar, vanilla, and chopped nuts. \n2. Form the mixture into small balls. \n3. Bake until lightly golden. \n4. Roll the warm cookies in powdered sugar. \n5. Serve as a delightful treat.'),
(66, 'Pav Bhaji', 'Indian', 'Main Course', 'Vegetarian', '1. Sauté onions, garlic, and ginger until golden brown. \n2. Add tomatoes, spices, and cooked mixed vegetables. \n3. Mash the vegetables and mix well. \n4. Serve the flavorful bhaji with buttered pav buns and chopped onions.'),
(67, 'Chicken Tortilla Soup', 'Mexican', 'Main Course', 'Non-Vegetarian', '1. Sauté onions, garlic, and bell peppers until softened. \n2. Add cooked chicken, diced tomatoes, broth, and spices. \n3. Simmer until the flavors meld. \n4. Serve with tortilla strips, avocado, cheese, and a squeeze of lime.'),
(68, 'Masala Dosa', 'Indian', 'Main Course', 'Vegetarian', '1. Make a fermented batter with rice and urad dal. \n2. Spread the batter into thin circles on a hot griddle. \n3. Drizzle with oil and cook until crispy. \n4. Fill the dosas with a spiced potato mixture. \n5. Serve with coconut chutney and sambar.'),
(69, 'Mexican Fruit Salad', 'Mexican', 'Side Dish', 'Vegetarian', '1. Dice a variety of fresh fruits such as mangoes, pineapple, watermelon, and berries. \n2. Toss the fruits with lime juice, chili powder, and salt for a sweet and tangy salad.'),
(70, 'Mysore Masala Dosa', 'Indian', 'Main Course', 'Vegetarian', '1. Make a fermented batter with rice, urad dal, and chana dal. \n2. Spread the batter into thin circles on a hot griddle. \n3. Smear spicy red chutney on the dosa. \n4. Fill the dosas with a spiced potato mixture. \n5. Serve with coconut chutney and sambar.'),
(71, 'Tortilla Soup', 'Mexican', 'Main Course', 'Any', '1. Sauté onions, garlic, and bell peppers until softened. \n2. Add diced tomatoes, broth, and spices. \n3. Simmer until the flavors meld. \n4. Garnish with tortilla strips, avocado, cheese, and a squeeze of lime.'),
(72, 'Medu Vada', 'Indian', 'Appetizer', 'Vegetarian', '1. Soak urad dal for a few hours and grind it into a smooth batter. \n2. Add spices and chopped onions to the batter. \n3. Shape the batter into donut-like rounds and deep fry until golden brown. \n4. Serve with coconut chutney and sambar.'),
(73, 'Mexican Rice Pudding (Arroz con Leche)', 'Mexican', 'Dessert', 'Vegetarian', '1. Rinse rice and cook it with milk, sugar, and cinnamon. \n2. Simmer until the rice is fully cooked and the pudding thickens. \n3. Serve warm or chilled, sprinkled with ground cinnamon.'),
(74, 'Pani Puri', 'Indian', 'Appetizer', 'Vegetarian', '1. Make small hollow puris from semolina or wheat flour. \n2. Fill the puris with a mixture of boiled potatoes, chickpeas, and tamarind chutney. \n3. Dunk the filled puris in spicy and tangy mint water. \n4. Serve immediately for a burst of flavors.'),
(75, 'Mexican Shrimp Cocktail', 'Mexican', 'Appetizer', 'Non-Vegetarian', '1. Mix cooked shrimp with diced tomatoes, onions, cucumber, and cilantro. \n2. Add lime juice, ketchup, and hot sauce for a tangy and spicy sauce. \n3. Serve chilled with avocado and saltine crackers.'),
(76, 'Kofta Curry', 'Indian', 'Main Course', 'Vegetarian', '1. Mix grated vegetables or paneer with spices and besan to form kofta balls. \n2. Fry the kofta balls until golden brown. \n3. Sauté onions, garlic, and ginger until golden brown. \n4. Add tomatoes and spices, and cook until the tomatoes break down. \n5. Stir in a creamy sauce and add the fried kofta balls. \n6. Serve with rice or naan.'),
(77, 'Mexican Flan', 'Mexican', 'Dessert', 'Vegetarian', '1. Make caramel by melting sugar until golden brown. \n2. Pour the caramel into ramekins. \n3. Prepare a custard mixture with eggs, sweetened condensed milk, evaporated milk, and vanilla. \n4. Pour the custard over the caramel in the ramekins. \n5. Bake until the flan is set. \n6. Refrigerate and invert the ramekins to serve.'),
(78, 'Aloo Samosa', 'Indian', 'Appetizer', 'Vegetarian', '1. Make a dough with all-purpose flour and water. \n2. Roll out the dough and cut it into circles. \n3. Stuff the circles with a mixture of spiced mashed potatoes and peas. \n4. Fold the circles into triangular samosas and seal the edges. \n5. Deep fry the samosas until golden brown. \n6. Serve with tamarind chutney.'),
(79, 'Mexican Chili', 'Mexican', 'Main Course', 'Any', '1. Sauté onions, garlic, and bell peppers until softened. \n2. Add ground beef or turkey and cook until browned. \n3. Stir in diced tomatoes, beans, broth, and spices. \n4. Simmer until the flavors meld and the chili thickens. \n5. Serve with shredded cheese and chopped green onions.'),
(80, 'Mango Kulfi', 'Indian', 'Dessert', 'Vegetarian', '1. Blend ripe mangoes, milk, condensed milk, and cardamom in a blender. \n2. Pour the mixture into molds or cups. \n3. Freeze until the kulfi is set. \n4. Serve as a delightful frozen treat.'),
(81, 'Fish Curry', 'Indian', 'Main Course', 'Non-Vegetarian', '1. Sauté onions, garlic, and ginger until softened. \n2. Add spices and cook until fragrant. \n3. Stir in chopped tomatoes and cook until they break down. \n4. Add fish fillets and cook until fully cooked. \n5. Garnish with chopped cilantro and serve with rice or naan.'),
(82, 'Champurrado', 'Mexican', 'Beverage', 'Vegetarian', '1. Heat milk and whisk in masa harina, chocolate, and spices. \n2. Cook until the mixture thickens and the chocolate is fully melted. \n3. Serve as a warm and comforting drink, similar to hot chocolate.'),
(83, 'Mutton Korma', 'Indian', 'Main Course', 'Non-Vegetarian', '1. Sauté onions, garlic, and ginger until softened. \n2. Add spices and cook until fragrant. \n3. Stir in chopped tomatoes and cook until they break down. \n4. Add cubed mutton and cook until tender. \n5. Garnish with chopped cilantro and serve with rice or naan.'),
(84, 'Mexican Cornbread', 'Mexican', 'Side Dish', 'Vegetarian', '1. Mix cornmeal, flour, baking powder, and spices. \n2. Stir in corn kernels, chopped jalapeños, and shredded cheese. \n3. Bake until golden brown and cooked through. \n4. Serve as a delicious accompaniment to any Mexican meal.'),
(85, 'Rasgulla', 'Indian', 'Dessert', 'Vegetarian', '1. Make small balls from paneer and semolina dough. \n2. Boil the balls in sugar syrup until they puff up. \n3. Serve chilled, soaking in the syrup.'),
(86, 'Mexican Guacamole Salad', 'Mexican', 'Side Dish', 'Vegetarian', '1. Mix diced avocados, tomatoes, onions, cilantro, and lime juice. \n2. Season with salt, pepper, and chili powder. \n3. Serve as a refreshing and healthy salad or side dish.'),
(87, 'Shahi Paneer', 'Indian', 'Main Course', 'Vegetarian', '1. Sauté onions, garlic, and ginger until golden brown. \n2. Add spices and cook until fragrant. \n3. Stir in chopped tomatoes and cook until they break down. \n4. Add paneer cubes and cook until heated through. \n5. Stir in cream and butter for richness. \n6. Garnish with chopped cilantro and serve with rice or naan.'),
(88, 'Spaghetti Carbonara', 'Italian', 'Main Course', 'Non-Vegetarian', '1. Cook spaghetti according to package instructions. \n2. In a bowl, mix eggs, grated cheese, black pepper, and chopped bacon. \n3. Drain cooked spaghetti and immediately toss it with the egg mixture. \n4. The heat from the spaghetti will cook the eggs and create a creamy sauce. \n5. Serve hot and enjoy!'),
(89, 'Vegetable Biryani', 'Indian', 'Main Course', 'Vegetarian', '1. Soak basmati rice for 30 minutes and drain. \n2. In a large pot, layer cooked vegetables and rice with saffron-infused milk and fried onions. \n3. Cover and cook on low heat until the rice is fully cooked and fragrant. \n4. Serve hot with raita and enjoy!'),
(90, 'Tacos Al Pastor', 'Mexican', 'Main Course', 'Non-Vegetarian', '1. Marinate thinly sliced pork with pineapple, onions, and spices. \n2. Grill the marinated pork until tender and slightly charred. \n3. Warm corn tortillas and fill them with the grilled pork and your favorite toppings. \n4. Serve with salsa and lime wedges. Enjoy your delicious tacos!'),
(91, 'Chocolate Brownies', 'Dessert', 'Dessert', 'Vegetarian', '1. Melt butter and chocolate in a double boiler. \n2. Mix in sugar, eggs, and vanilla until well combined. \n3. Add flour and cocoa powder and fold until just combined. \n4. Pour the batter into a greased baking pan and bake until a toothpick inserted in the center comes out with moist crumbs. \n5. Let it cool, cut into squares, and enjoy your gooey chocolate brownies!'),
(92, 'Vegan Lentil Soup', 'Any', 'Main Course', 'Vegan', '1. Sauté onions, garlic, carrots, and celery in olive oil until softened. \n2. Add lentils, vegetable broth, tomatoes, and your favorite spices. \n3. Bring to a boil, then simmer until the lentils are tender. \n4. Adjust seasonings to taste and serve hot with a sprinkle of fresh herbs. Enjoy your hearty vegan lentil soup!'),
(93, 'Spaghetti Carbonara', 'Italian', 'Main Course', 'Non-Vegetarian', '1. Cook spaghetti according to package instructions. \n2. In a bowl, mix eggs, grated cheese, black pepper, and chopped bacon. \n3. Drain cooked spaghetti and immediately toss it with the egg mixture. \n4. The heat from the spaghetti will cook the eggs and create a creamy sauce. \n5. Serve hot and enjoy!'),
(94, 'Vegetable Biryani', 'Indian', 'Main Course', 'Vegetarian', '1. Soak basmati rice for 30 minutes and drain. \n2. In a large pot, layer cooked vegetables and rice with saffron-infused milk and fried onions. \n3. Cover and cook on low heat until the rice is fully cooked and fragrant. \n4. Serve hot with raita and enjoy!'),
(95, 'Tacos Al Pastor', 'Mexican', 'Main Course', 'Non-Vegetarian', '1. Marinate thinly sliced pork with pineapple, onions, and spices. \n2. Grill the marinated pork until tender and slightly charred. \n3. Warm corn tortillas and fill them with the grilled pork and your favorite toppings. \n4. Serve with salsa and lime wedges. Enjoy your delicious tacos!'),
(96, 'Chocolate Brownies', 'Dessert', 'Dessert', 'Vegetarian', '1. Melt butter and chocolate in a double boiler. \n2. Mix in sugar, eggs, and vanilla until well combined. \n3. Add flour and cocoa powder and fold until just combined. \n4. Pour the batter into a greased baking pan and bake until a toothpick inserted in the center comes out with moist crumbs. \n5. Let it cool, cut into squares, and enjoy your gooey chocolate brownies!'),
(97, 'Vegan Lentil Soup', 'Any', 'Main Course', 'Vegan', '1. Sauté onions, garlic, carrots, and celery in olive oil until softened. \n2. Add lentils, vegetable broth, tomatoes, and your favorite spices. \n3. Bring to a boil, then simmer until the lentils are tender. \n4. Adjust seasonings to taste and serve hot with a sprinkle of fresh herbs. Enjoy your hearty vegan lentil soup!'),
(98, 'Spaghetti Carbonara', 'Italian', 'Main Course', 'Non-Vegetarian', '1. Cook spaghetti according to package instructions. \n2. In a bowl, mix eggs, grated cheese, black pepper, and chopped bacon. \n3. Drain cooked spaghetti and immediately toss it with the egg mixture. \n4. The heat from the spaghetti will cook the eggs and create a creamy sauce. \n5. Serve hot and enjoy!'),
(99, 'Vegetable Biryani', 'Indian', 'Main Course', 'Vegetarian', '1. Soak basmati rice for 30 minutes and drain. \n2. In a large pot, layer cooked vegetables and rice with saffron-infused milk and fried onions. \n3. Cover and cook on low heat until the rice is fully cooked and fragrant. \n4. Serve hot with raita and enjoy!'),
(100, 'Tacos Al Pastor', 'Mexican', 'Main Course', 'Non-Vegetarian', '1. Marinate thinly sliced pork with pineapple, onions, and spices. \n2. Grill the marinated pork until tender and slightly charred. \n3. Warm corn tortillas and fill them with the grilled pork and your favorite toppings. \n4. Serve with salsa and lime wedges. Enjoy your delicious tacos!'),
(101, 'Chocolate Brownies', 'Dessert', 'Dessert', 'Vegetarian', '1. Melt butter and chocolate in a double boiler. \n2. Mix in sugar, eggs, and vanilla until well combined. \n3. Add flour and cocoa powder and fold until just combined. \n4. Pour the batter into a greased baking pan and bake until a toothpick inserted in the center comes out with moist crumbs. \n5. Let it cool, cut into squares, and enjoy your gooey chocolate brownies!'),
(102, 'Vegan Lentil Soup', 'Any', 'Main Course', 'Vegan', '1. Sauté onions, garlic, carrots, and celery in olive oil until softened. \n2. Add lentils, vegetable broth, tomatoes, and your favorite spices. \n3. Bring to a boil, then simmer until the lentils are tender. \n4. Adjust seasonings to taste and serve hot with a sprinkle of fresh herbs. Enjoy your hearty vegan lentil soup!');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `recipes`
--
ALTER TABLE `recipes`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `recipes`
--
ALTER TABLE `recipes`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=103;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
